.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This file is part of Iagno.
.\"
.\" Iagno is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" Iagno is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with Iagno. If not, see <http://www.gnu.org/licenses/>.
.TH IAGNO 6 "2014\-02\-08" "GNOME"
.SH NAME
Iagno \- A disk flipping game derived from Reversi
.SH SYNOPSIS
.B iagno
.RI [ OPTION... ]
.SH DESCRIPTION
Iagno is a two\-player strategy game similar to Go.  The board is 8 by
8 with tiles that are black on one side and white on the other side.
The object of Iagno is to flip as  many of your opponent's tiles to
your color as possible without your opponent flipping your tiles.
This is done by trapping your opponent's tiles between two tiles of
your own color.
.SH OPTIONS
.TP
.B \-\-alternative\-start
Start the game with an alternative position.
.TP
.B \-f, \-\-fast\-moves
Play with reduced delay before the computer moves.
.PP
.B \-\-first
.br
.B \-\-second
.br
.B \-\-two-players
.RS 7
Sets the game mode.
.br
The options --first and --second are for a one-player game,
where the player plays respectively first and second.
.br
The option --two-players is for a two-players game mode.
.br
You should only use one of these options at the same time.
.RE
.TP
.B \-h, \-\-help
Prints the command line options and exits.
.TP
.B \-l, \-\-level=<level>
Changes the computer's AI level (1-3).
.br
1 is the easiest, 2 is good, 3 is the hardest.
.PP
.B \-\-mute
.br
.B \-\-unmute
.RS 7
Turn off/on the sound.
.br
If the two options are given, the game is muted.
.RE
.TP
.B \-s, \-\-size=<size>
Changes the size of the board. The size must be at least 4.
.br
This option is for debugging only. The AI may not perform optimally.
.TP
.B \-v, \-\-version
Prints the program version and exits.
.P
This program also accepts the standard GTK+ options.
.SH AUTHORS
.B iagno
was written by Ian Peters.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian project (but may be used by others).
